// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvfzGVo9jb1S-JE44Wjhmg4KMXftd0izw',
    appId: '1:372285921840:web:a919fcbbe71118926a2bf5',
    messagingSenderId: '372285921840',
    projectId: 'clipr-ecd2d',
    authDomain: 'clipr-ecd2d.firebaseapp.com',
    storageBucket: 'clipr-ecd2d.appspot.com',
    measurementId: 'G-JN78CLJM1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkK95X1VrePmspjFKCmMHbKaL-jq7D-sM',
    appId: '1:372285921840:android:dd128736588463146a2bf5',
    messagingSenderId: '372285921840',
    projectId: 'clipr-ecd2d',
    storageBucket: 'clipr-ecd2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTeeYcSZoqcslDvk3isqtCCd4H_PWr2fI',
    appId: '1:372285921840:ios:231f90bab23f499a6a2bf5',
    messagingSenderId: '372285921840',
    projectId: 'clipr-ecd2d',
    storageBucket: 'clipr-ecd2d.appspot.com',
    iosClientId: '372285921840-m3aj5kntm1q3kaps9qanqhobh96mrdh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.clipr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTeeYcSZoqcslDvk3isqtCCd4H_PWr2fI',
    appId: '1:372285921840:ios:373a046f039808aa6a2bf5',
    messagingSenderId: '372285921840',
    projectId: 'clipr-ecd2d',
    storageBucket: 'clipr-ecd2d.appspot.com',
    iosClientId: '372285921840-nt670tv20aq8sc40cdv1t3ek58gcqehf.apps.googleusercontent.com',
    iosBundleId: 'com.example.clipr.RunnerTests',
  );
}
